Develop
ACKAPOB/java-explore-with-me pull request #2
Opened 2023-01-12 18:28 UTC by ACKAPOB

2023-01-18 17:07 UTC, EugeneLenkevich requested changes
Привет, Игорь, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай, не стесняйся, немножко допилить осталось :)

В целом все нормально, замечания в принципе по мелочи, единственное, будь поаккуратней с именами методов, все таки код пишется в первую очередь для другого разработчика, который его потом будет поддерживать, потому это очень важно :)

Удачи!

PS
в редми, кстати, в приложенном архиве, не было ссыли на ПР :)

2023-01-18 17:07 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/explore/event/service/AdminEventService.java
> +    EventFullDto approveRejectEvent(Long eventId);
Не совсем понятно что делает метод approveRejectEvent, то approve, то ли reject - это две противоположные операции, может все таки rejectEvent :)
Выше аналогично)

2023-01-18 17:07 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/explore/user/repository/UserRepository.java
> +    @Query("select u from User u where u.id IN ?1 order by u.id")
Опять таки order by u.id можно убрать так как есть pageable :)

2023-01-18 17:07 UTC, EugeneLenkevich commented on stats-service/src/main/java/ru/practicum/explore/repository/StatsRepository.java
> +    @Query("SELECT new ru.practicum.explore.model.ViewStats(e.app, e.uri, COUNT(e.id)) " +
Супер!

2023-01-19 07:43 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/category/service/AdminCategoryService.java
> +    CategoryDto patchCategory(CategoryDto categoryDto);
Пробежался по классам, убрал лишнюю инфу из названий классов!

2023-01-19 07:43 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/compilation/mapper/CompilationMapper.java
> +    public static Compilation toCompilation(NewCompilationDto compilationDto, List<Event> events) {
Поигрался с стат. методами и хватит )!

2023-01-19 07:44 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/compilation/service/impl/AdminCompilationServiceImpl.java
> +    public void pinCompilation(Long compId) {
Поправил!

2023-01-19 07:44 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/compilation/service/impl/PublicCompilationServiceImpl.java
> +    public List<CompilationDto> getCompilationAll(Boolean pinned, Integer from, Integer size) {
Поправил!

2023-01-19 07:44 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/event/service/AdminEventService.java
> +    EventFullDto approveRejectEvent(Long eventId);
Поправил!

2023-01-19 10:20 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/controllers/adminController/AdminEventController.java
> +            @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeStart,
Добавил класс JacksonObjectMapperAutoConfiguration

2023-01-19 10:21 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/event/repository/EventRepository.java
> +            "order by e.id")
Поправил!

2023-01-19 10:22 UTC, ACKAPOB commented on main-service/src/main/java/ru/practicum/explore/user/repository/UserRepository.java
> +    @Query("select u from User u where u.id IN ?1 order by u.id")
Ну да убрал!

2023-01-19 15:13 UTC, EugeneLenkevich approved these changes
Спасибо, все супрер!

Единственное, к самой задаче приложи, пожалуйста, актуальный архив и исходниками, лучше думаю соблюсти это формальность :)

![image](https://user-images.githubusercontent.com/109306643/213479646-0c0f06a3-e3f4-4557-9207-173ae426de5d.png)

2023-02-13 16:13 UTC, merged